package dp5

/*
Problem Description
Given a string A, find if there is any subsequence that repeats itself.

A subsequence of a string is defined as a sequence of characters generated by deleting some characters in the string without changing the order of the remaining characters.

NOTE:
1. Subsequence length should be greater than or equal to 2.
2. The repeating subsequence should be disjoint that is in both the sequence no character in the same order and position should be taken from the same index of the original string.

Problem Constraints
1 <= length(A) <= 100

Input Format
The first and the only argument of input contains a string A.

Output Format
Return an integer, 1 if there is any subsequence which repeat itself else return 0.

Example Input
Input 1:
A = "abab"

Input 2:
A = "abba"

Example Output
Output 1:
1

Output 2:
0

Example Explanation
Explanation 1:
"ab" is repeated.

Explanation 2:
There is no repeating subsequence.
*/
func HasRepeatingSubSeq(A string) int {
	if getLongestLCS(A, A) >= 2 {
		return 1
	}
	return 0
}

func getLongestLCS(A, B string) int {
	source := A
	target := B
	N := len(source)
	M := len(target)

	memo := make([][]int, N+1)
	for i := range memo {
		memo[i] = make([]int, M+1)
	}

	for i := 1; i <= N; i++ {
		for j := 1; j <= M; j++ {
			//if i and j are not same but characters are same
			if source[i-1] == target[j-1] && i != j {
				memo[i][j] = 1 + memo[i-1][j-1]
			} else {
				memo[i][j] = max(memo[i-1][j], memo[i][j-1])
			}
		}
	}
	return memo[N][M]
}
